# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: auto build page

on:
  workflow_dispatch: 
  push:
     branches: [ "main" ]
     paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
       - README.md
       - ".github/**"
  pull_request:
     branches: [ "main" ]
     paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
       - README.md
       - ".github/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
          node-version: 20
    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: ${{ runner.OS }}-npm-cache
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build-linux

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./build
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2    
